version: '3.3'

services:
  frontend: # front end container (running frontend project in nginx)
      container_name: frontend
      restart: always
      build:         
            context: ./app          
      volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf # mount nginx configuration
      environment:
              NODE_ENV: development
      ports:
        - 8086:80 # mapping port
      networks:
      - frontend_net

  nginx_fr:
    image: nginx:latest
    container_name: nginx_front
    restart: unless-stopped
    build:
            context: ./nginx
    ports:
      - 8085:80
    networks:
      - frontend_net



networks:
    frontend_net:
        driver: bridge  