version: '3'
services:

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    networks:
      - frontend_net


  frontend: # front end container (running frontend project in nginx)
      container_name: frontend
      restart: always
      build:         
            context: ./app 
         
      volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf # mount nginx configuration

      environment:
              NODE_ENV: development
      ports:
        - 80:80 # mapping port
      networks:
      - frontend_net

networks:
    frontend_net:
        driver: bridge  