version: "3.4"
services:
        nodeserver:
            build:
                context: ./app
            environment:
                  NODE_ENV: development
            ports:
                - "5000:5000"
        nginx:
            restart: always
            build:
                context: ./nginx
            environment:
                  NODE_ENV: development
            ports:
                - "80:80"