version: '3.3'

services:
  backend: # front end container (running frontend project in nginx)
      # container_name: backend
      restart: always
      build:         
            context: ./app          
      volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf # mount nginx configuration

      environment:
              NODE_ENV: development
      ports:
        - 5000:5000
      networks:
      - frontend_net

  nginx: 
    image: nginx:latest
    container_name: nginx_back
    build:
            context: ./nginx
    ports:
      - 80:80  
    networks:
      - frontend_net

networks:
    frontend_net:
        driver: bridge  